name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 17
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'joshlucpoll'
        reponame: 'esp-website'
        cname: 'esp.joshlucpoll.dev'
        useyarn: true
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
